version: "3.5"

services:
    tokenservice:
        image: ficodes/token-service:0.2
        depends_on:
            - keyrock
        environment:
            - ACCESS_TOKEN_URL=http://keyrock:3000/oauth2/token
            - TOKEN_SERVICE_CLIENT_ID=API_ACCESS_ID
            - TOKEN_SERVICE_CLIENT_SECRET=API_ACCESS_SECRET
        networks:
            - front
        deploy:
            replicas: 1
            restart_policy:
                condition: any

networks:
    front:
        driver: overlay
        ipam:
            config:
                - subnet: 172.40.0.0/16